config/routes.rb
Assistance::Application.routes.draw do

  devise_for :users 
  devise_scope :user do
    get "/login",   to: "sso_sessions#show"
    get '/logout',  to: "sso_sessions#destroy"
    post '/logout', to: "sso_sessions#destroy"
  end
  resource :sso_session

  get "/ping", to: "ping#ping"

  post 'sns', to: 'message_door#sns'
  root 'attendances#index'

  resources :time_slots do
    collection do
      get :vacancies
    end
    member do
      get :sync_to_learn
    end
  end
  resources :attendances
  resources :attendance_contacts, only: [:index]
  get 'attendances_details', to: "attendance_contacts#index"
  resources :trial_lessons
  resources :contacts, :only => [:index, :show, :update]
  resources :stats, :only => [:index] do
    collection do
      get 'attendances_by_teacher', to: "stats#attendances_by_teacher"
      get 'current_month', as: 'current_month', to: 'stats#index', easy_period: :current_month
      get 'last_month', as: 'last_month', to: 'stats#index', easy_period: :last_month
    end
  end

  namespace 'api' do
    namespace 'v0' do
      resource :stats
      resources :merges, only: [:create]
      resources :trial_lessons, only: [:index]
      resources :time_slots, only: [:show, :index]
      resources :attendance_contacts, only: [:create,:destroy]
      resources :contacts, only: [:show, :index] do
        collection do
          post :list, to: 'contacts#index'
        end
        member do
          get :last_trial
          post :sync_from_crm
        end
      end
      resources :imports, only: [:create, :show] do
        member do
          get :failed_rows # GET /api/v0/imports/:id/failed_rows
        end
      end
    end
  end
  

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  include LearnSync

  default_scope { where("deleted= :false OR deleted IS NULL", false: false).order('name ASC') }

  belongs_to :account
  
  has_many :contact_time_slots
  has_many :contacts, through: :contact_time_slots
  
  has_many :attendances

  has_many :trial_lessons, dependent: :nullify

  validates :account,  :presence => true
  validates :name,  :presence => true #, :uniqueness => {:scope => :account_id}
  validates_time :end_at, :after => :start_at

  # attr_accessible :padma_uid, :name, :start_at, :end_at, :padma_contacts, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :cultural_activity, :external_id, :unscheduled

  before_create :set_defaults

  scope :with_schedule, ->{ where("(monday = :true) or (tuesday = :true) or (wednesday = :true) or (thursday = :true) or (friday = :true) or (saturday = :true) or (sunday = :true)",true: true) }
  scope :without_schedule, ->{ where("(monday = :false OR monday IS NULL) and (tuesday = :false OR tuesday IS NULL) and (wednesday = :false OR wednesday IS NULL) and (thursday = :false OR thursday IS NULL) and (friday = :false OR friday IS NULL) and (saturday = :false OR saturday IS NULL) and (sunday = :false OR sunday IS NULL) and (unscheduled = :false OR unscheduled IS NULL)",false: false) }

  def description
    "#{self.name} (#{self.start_at.hour}#{minutes(self.start_at)}hs-#{self.end_at.hour}#{minutes(self.end_at)}hs)"
  end

  def minutes(hour)
    ":#{hour.min}" unless hour.min.zero?
  end

  def recurrent_contacts
    # Find recurrent_students
    rec_contacts = Attendance
                    .joins(:attendance_contacts)
                    .joins(:attendance_contacts => :contact)
    		    .joins(:attendance_contacts => {:contact => :accounts_contacts})
                    .where('accounts_contacts.account_id = ?', account.id)
                    .where('accounts_contacts.padma_status' => 'student') # Make sure they are still students
                    .where('attendances.time_slot_id' => self.id) # Consider only this timeslot
                    .where('attendances.attendance_on >= ?', 1.month.ago.beginning_of_month) # Filter those who attended this timeslot on the past month
                    .select("contacts.name as first_name, '' as last_name, contacts.padma_id as _id") # Select Contact fields and prepare return as PadmaContacts
    
    # Find this timeslot's students and select fields for result
    ts_contacts = self.contacts.students_on(account).select("contacts.name as first_name, '' as last_name, contacts.padma_id as _id").group('contacts.padma_id, contacts.name')
    
    # Join recurrent and timeslot students and order by name
    (ts_contacts+rec_contacts).uniq {|c| c._id}.sort{|a,b| a.first_name <=> b.first_name }
  end

  # WARNING this method persists it's changes automatically.
  def padma_contacts= padma_contacts
    if self.persisted?
      self.contact_time_slots.delete_all
      padma_contacts.each do |padma_contact_id|
        contact = Contact.get_by_padma_id(padma_contact_id,self.account_id)
        self.contact_time_slots.create(contact_id: contact.id)
      end
    end
  end

  def description_with_day
    description + " [#{time_slot_days}]"
  end

  def time_slot_days
    response = ""
    days = [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday]
    days.each do |day|
      if send(day)
        response += ", " unless response.empty?
        day_name = I18n.t('date.abbr_day_names')[days.find_index(day)+1]
        response += day_name unless day_name.nil?
      end
    end
    response
  end
  
  def scheduled_for_wday?(wday)
    days = [:sunday,:monday, :tuesday, :wednesday, :thursday, :friday, :saturday]
    send(days[wday])
  end

  private

  def set_defaults
    if self.cultural_activity.nil?
      self.cultural_activity = false
    end

    # return true to avoid this filter breaking the callback queue.
    return true
  end

end

app/models/time_slot/learn_sync.rb
require "learn_api"

module TimeSlot::LearnSync
  extend ActiveSupport::Concern

  included do

  end

  def get_from_learn
    if defined? @got_from_learn
      @got_from_learn
    else
      res = api.get(
        "/posts.json",
        {
          scope: "all",
          q: {
            padma_time_slot_id_eq: id,
          }
        }
      )
      @got_from_learn = res.try :first
    end

  end

  def sync_to_learn
    if learn_account
      if get_from_learn
        update_on_learn
      else
        create_on_learn
      end
    end
  end

  def create_on_learn
    if learn_account && !get_from_learn
      api.post("/in_person_lives.json", {in_person_live: learn_post_attributes})
    end
  end

  def update_on_learn
    if learn_account && (learn_post = get_from_learn)
      learn_id = learn_post["id"]
      api.put("/posts/#{learn_id}.json", {post: learn_post_attributes})
    end
  end

  private

  def learn_post_attributes
    ret ={
      padma_time_slot_id: id,
      title: name,
      owner_account_id: learn_account["id"],
      slug: "padma_time_slot_#{id}",
      private_body: observations,
      visibility: "account_users",
      live_starts_at: start_at.strftime("%Y-%m-%d %H:%M").to_time, # para que esté en timezone pero sin cambiar horario
      live_ends_at: end_at.strftime("%Y-%m-%d %H:%M").to_time, # para que esté en timezone pero sin cambiar horario
      booking_wont_consume_quota: cultural_activity?,
      weekly_post: true,
      wday_0: sunday? && !unscheduled?,
      wday_1: monday? && !unscheduled?,
      wday_2: tuesday? && !unscheduled?,
      wday_3: wednesday? && !unscheduled?,
      wday_4: thursday? && !unscheduled?,
      wday_5: friday? && !unscheduled?,
      wday_6: saturday? && !unscheduled?,
    }
    if deleted?
      ret.merge({
        published_until: 1.day.ago
      })
    end
    ret
  end

  def learn_account
    api.get("/accounts.json", {q: {padma_id_eq: account.name}}).try :first
  end

  def api
    @api ||= LearnApi.new
  end



end

app/controllers/api/v0/time_slots_controller.rb
class Api::V0::TimeSlotsController < Api::V0::ApiController
  include Api::V0::TimeSlotsHelper
  respond_to :json
  
  authorize_resource
  
  before_filter :set_scope
  
  # @param account_name filters TimeSlots by account
  # @param include_recurrent_contacts
  def index
    @scope = @scope.where(params[:where].try(:to_unsafe_h))
    @time_slots = @scope.includes(:account, :contacts).all
    render json: {
      collection: api_json_for_collection(@time_slots,
        { include_recurrent_contacts: to_bool(params[:include_recurrent_contacts]) }
      ),
      total: @time_slots.count
    }
  end
  
  def show
    @time_slot = TimeSlot.find(params[:id])
    render json: api_json(
      @time_slot,
      {include_recurrent_contacts: to_bool(params[:include_recurrent_contacts])}
    )
  end
  
  private

  def set_scope
    @scope = TimeSlot.all
    if params[:account_name]
      @account = Account.find_by_name params[:account_name]
      if @account
        @scope = @scope.where(account_id: @account.id)
      else
        @scope = @scope.none
      end
    end
    # TODO filter by contact (for frequently assisted)
    # TODO filter by contact (for inscription in timeslot)
  end
  
  # cast strings 'f', 'false', '0' to FALSE
  def to_bool(string)
    return false if string.nil?
    return false if string.in?(%W(false 0 f))
    !!string
  end
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController

  before_filter :load_time_slot, only: [:create, :update]
  before_filter :update_timeslot_params, only: [:create, :update]
  load_and_authorize_resource

  def index
    @unscheduled_time_slots = @time_slots.where(unscheduled: true)
    @time_slots = @time_slots.with_schedule
  end

  def show
    @students = @time_slot.contacts.students_on(current_user.current_account)
    @regular_participants = @time_slot.recurrent_contacts
    @attendances_by_month = @time_slot.attendances
                                      .where("attendance_on > ?",3.months.ago)
                                      .order('attendance_on DESC')
                                      .group_by { |att| att.attendance_on.beginning_of_month }
    respond_to do |format|
      format.html
      format.json { render json: @time_slot }
    end
  end

  def sync_to_learn
    @time_slot = TimeSlot.find(params[:id])
    if @time_slot.sync_to_learn
      redirect_to @time_slot
    else
      redirect_to @time_slot
    end
  end

  def vacancies
    @time_slots = @time_slots.where(cultural_activity: false)
  end

  def new
  end

  def edit
  end  
  
  def create
    if @time_slot.save
      redirect_to @time_slot, notice: 'Time slot was successfully created.'
    else
      render action: 'new'
    end
  end

  def update    
    respond_to do |format|
      if @time_slot.update(update_timeslot_params)
        format.html {
          redirect_to @time_slot, notice: 'Time slot was successfully updated.'
      	}
      	format.json { render json: { success: true }}
      else
      	format.html {
                render action: 'edit'
      	}
      	format.json {
                render json: @time_slot.errors, status: :unprocessable_entity
      	}
      end
    end
  end

  def destroy
    # @time_slot initialized by load_and_authorize_resource
    # @time_slot.destroy
    @time_slot.update_attribute(:deleted, true)
    redirect_to time_slots_url, notice: t('time_slots.destroy.success')
  end	
  
  private

  def time_slot_params
    if params.has_key?(:time_slot) && !params[:time_slot].blank?
      params.require(:time_slot).permit(
        :padma_uid,
        :name,
        :start_at,
        :end_at,
        :monday,
        :tuesday,
        :wednesday,
        :thursday,
        :friday,
        :saturday,
        :sunday,
        :cultural_activity,
        :external_id,
        :unscheduled,
        :padma_contacts => []
      )
    else
      {}
    end
  end

  def load_time_slot
    if params.has_key?(:id)
      @time_slot = TimeSlot.find(params[:id])
      @time_slot.account = current_user.current_account
    else
      @time_slot = TimeSlot.new(update_timeslot_params)
      @time_slot.account = current_user.current_account
    end
  end

  def update_timeslot_params
    permitted_params = time_slot_params
    selected_day_names = params[:dayname] ? params[:dayname].map{|day| day.downcase} : []
    permitted_params.delete(:dayname)
    Date::DAYNAMES.each do |day_name|
      day_name = day_name.downcase
      # params[:time_slot][day_name.to_sym] = (selected_day_names.include? day_name) ? "1" : "0"
      permitted_params[day_name.to_sym] = (selected_day_names.include? day_name) ? "1" : "0"
      
    end
    permitted_params
  end 

end

app/helpers/api/v0/time_slots_helper.rb
module Api::V0::TimeSlotsHelper
    
  # maps time_slots collection to JSON
  # option :include_recurrent_contacts will add recurrent_contacts array of IDS
  # option :
  # 
  def api_json_for_collection(time_slots, options={})
    time_slots.map do |t|
      api_json(t,options)
    end
  end
  
  def api_json(time_slot, options={})
    ret = {
      id: time_slot.id,
      name: time_slot.name,
      description: time_slot.description,
      start_at: time_slot.start_at.strftime('%H:%M'),
      end_at: time_slot.end_at.strftime('%H:%M'),
      schedule: time_slot.unscheduled?? '-' : time_slot.time_slot_days,
      account_name: time_slot.account.try(:name),
      teacher: time_slot.padma_uid,
      contacts: time_slot.contacts.map(&:padma_id)
    }
    if options[:include_recurrent_contacts]
      ret.merge!({recurrent_contacts: time_slot.recurrent_contacts.map(&:_id)})
    end
    ret
  end
  
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
  
  def already_selected_day_name
    selected_day = []
    Date::DAYNAMES.map{|day| day.downcase}.each do |day_name|
      selected_day << day_name.capitalize if @time_slot[day_name]
    end  
    selected_day
  end

  def showSchedule( time_slot )
    days = I18n.t('date.abbr_day_names')
    ret = []
    [time_slot.sunday,time_slot.monday,time_slot.tuesday,time_slot.wednesday,time_slot.thursday,time_slot.friday,time_slot.saturday,time_slot.sunday].each_with_index do |day,i|
      if day
        ret << days[i]
      end
    end
    ret.compact.join(',')
  end
  
  def crm_contacts_list_url( time_slot )
    columns_query = %W(full_name local_teacher level time_since_first_enrollment last_seen_at membership_name membership_value).map{|col| "contact_search[chosen_columns][]=#{col}" }.join('&')
    "#{APP_CONFIG['crm-url']}/contacts?contact_search[linked_to_time_slot_ids][]=#{time_slot.id}&#{columns_query}"
  end

end

app/views/time_slots/_form.html.erb
<div class="row" id="time_slot">
  <div class ="col-xs-12 col-sm-9 col-md-5">
    <%= form_for @time_slot, :html => { :class => 'form-horizontal' } do |f| %>
      <% if @time_slot.errors.any? %>
        <div id="error_explanation">
          <p class='bg-warning'><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</p>
          <ul class='list-unstyled margin-bottom-10'>
            <% @time_slot.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class='form-group'>
        <%= f.label :name, :class => 'control-label col-xs-5 col-md-4' %>
        <div class="col-xs-7 col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "input name" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :start_at, :class => 'control-label col-xs-5 col-md-4' %>
        <div class="col-xs-7 col-md-8 start-end-date">
          <%= f.time_select :start_at, {:minute_step => 05} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :end_at, :class => 'control-label col-xs-5 col-md-4' %>
        <div class="col-xs-7 col-md-8 start-end-date">
          <%= f.time_select :end_at, {:minute_step => 05} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :padma_uid, :class => 'control-label col-xs-5 col-md-4' %>
        <div class="col-xs-7 col-md-8 instrutor_select">
          <%= f.select :padma_uid,
            current_user.current_account.usernames.map{|u| [User.full_name_for(u),u]}, 
            {},
            class: 'selectpicker' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-xs-5 col-md-4"></div>
        <div class="col-md-8 col-xs-7 checkbox">
          <%= f.check_box :cultural_activity %> <%= f.label :cultural_activity, :class => '' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-4 col-xs-5"></div>
        <div class="col-md-8 col-xs-7 checkbox">
          <%= f.check_box :unscheduled %> <%= f.label :unscheduled %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :schedule, :class => 'control-label col-xs-5 col-md-4' %>
        <div class="col-xs-7 col-md-8">
          <%= select_tag "dayname", options_for_select(Date::DAYNAMES, already_selected_day_name), multiple: true, class: 'multiselect'%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :padma_contacts, :class => 'control-label col-xs-5 col-md-4' %>
        <div class="col-md-8 col-sm-8 col-xs-7">
          <ul id="time_slot_students" class='list-unstyled'>
            <% @time_slot.contacts.students_on(current_user.current_account).each do |c| %>
              <li>
                <%= hidden_field_tag "time_slot[padma_contacts][]", c.padma_id %><%= link_to "#{c.name}", "#", :class => "delete" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>

      <% if @time_slot.persisted? -%>
        <div class="form-group">
          <%= f.label :add_a_contact, :class => 'control-label col-xs-5 col-md-4' %>
          <div class="col-xs-7 col-md-8">
            <%= select_tag :padma_contacts_select, options_for_select({"" => :empty, "All students" => :all_students}.merge(Hash[current_user.current_account.usernames.map {|username| ["#{username}'s students", username].flatten}])), class: 'selectpicker select_btn_width' %>
            <%= image_tag("ajax-loader.gif", id:"loading") %>
            <fieldset id="time_slot_padma_contacts">
              <%= render :partial => 'shared/padma_contacts' %>
            </fieldset>
          </div>
        </div>
      <% end -%>

      <div class="form-footer margin-top-20">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to 'Show', @time_slot, :class => 'btn btn-link' if @time_slot.persisted? %>
        <%= link_to t('destroy'), @time_slot, :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
        <%= link_to 'Cancel', time_slots_path, :class => 'btn btn-link' %>
      </div>
    <% end %>
  </div>
</div>

app/views/time_slots/_time_slot.html.erb
<li class="list-group-item">
  <header class='timeslot-head'><%= link_to time_slot.name, time_slot %></header>
  <div class='timeslot-content'>
    <div class='timeslot-description'>
      <p>
        <%= time_slot.time_slot_days %><br/>
        <%= timeslot_period(time_slot) %><br/>
        <%= User.full_name_for(time_slot.padma_uid) %>
      </p>
      
      <span class='results-count-attendances' tabindex='0' data-toggle='popover' data-container='body' data-placement='bottom' data-html='true' data-trigger='focus' data-content='
        <div class="students-list">
          <% time_slot.contacts.each do |contact| %>
            <%= link_to_contact_profile(contact) %>
          <% end %>
        </div>'>
        (<%= time_slot.contacts.count %>)
      </span>
    </div>
    <div class='timeslot-controls'>
      <%= link_to t('edit'), edit_time_slot_path(time_slot), :class => 'btn btn-primary btn-xs btn-block' %>
      <%= link_to t('destroy'), time_slot, confirm: t('confirm'), method: :delete, class: 'btn btn-danger btn-xs btn-block' %>
    </div>
  </div>
</li>

app/views/time_slots/edit.html.erb
<%- breadcrum t("time_slots.edit.title") -%>
<%= render 'form' %>

app/views/time_slots/index.html.erb
<%- breadcrum t("time_slots.index.title") -%>
<% content_for :title do t("time_slots.index.title") end -%>

<div class="alert alert-info">
  <p>
    No <b>Learn DeROSE</b> tem uma app nova para marcar presenças mas com check-ins. Pode ver <%= link_to "aquí", "https://learn.derose.app/teacher_panel", target: "_blank" %>.
    <br>
    Recomendamos você passar a usar os check-ins do Learn no lugar das presenças. Fica bem mais prático e você tem mais opções nos relatórios. Você pode incluir ou não check-ins em videos. Você pode ver participação de seus alunos em aulas ou conteúdos de outras escolas. E muito mais!
    <br>
    Você pode fazer chamada de forma rápida com o app do Instrutor do Learn ou ainda melhor, ter os check-ins cadastrados de forma AUTOMÁTICA 😃. Veja mais <%= link_to "aquí", "https://deroseapp.notion.site/Check-ins-Presen-as-aprimoradas-e0175e32433149d88ba6aa8e475a581a", target: "_blank" %>
  </p>
</div>

<div id="search-field-container" class='margin-bottom-20'>
  <input id="timeslots-filter" class='form-control' type='text' placeholder='<%= t('.filter_timeslots') %>' />
</div>

<div class='attendance-container'>
  <nav class='attendance-navbar margin-bottom-10' role='navigation'>
    <div class="filter-controls">
      
    </div>
    
    <div class='filter-controls filter-controls-right'>
      <%= link_to t('time_slots.index.new'), new_time_slot_path, class: 'btn btn-primary' %>
    </div>
  </nav>

  <section class='attendance-body'>
    <% (1..7).each do |wday| %>
      <div class="panel panel-default">
        <div class="panel-heading" >
          <%= t('date.day_names')[wday%7].capitalize %>
        </div>
        <div class="panel-body">
          <ul class="list-group">
            <% @time_slots.select{|ts| ts.scheduled_for_wday?(wday%7) }
                          .sort_by{|ts| ts.start_at.strftime("%H:%M") }
                          .each do |time_slot| %>
              <div>
                <%= render 'time_slot', time_slot: time_slot %>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </section>
</div>

<% unless @unscheduled_time_slots.empty? %>
<table id="timeslots" class="table table-striped">
  <thead>
    <tr>
      <th><%= TimeSlot.human_attribute_name(:name) %></th>
      <th><%= TimeSlot.human_attribute_name(:padma_uid) %></th>
      <th><%= t('.quantity_signed_up') %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @unscheduled_time_slots.each do |ts| %>
      <tr>
        <td>
          <%= link_to ts.name, ts %>
        </td>
        <td><%= ts.padma_uid %></td>
        <td><%= link_to ts.contacts.count, crm_contacts_list_url(ts), target: '_blank' %></td>
        <td class='td-actions'>
          <%= link_to t('edit'), edit_time_slot_path(ts), :class => 'btn secondary btn-xs' %>
        </td>
        <td>
          <%= link_to t('destroy'), ts, confirm: t('confirm'), method: :delete, class: 'delete-btn btn btn-mini btn-link' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/time_slots/new.html.erb
<%- breadcrum t("time_slots.index.new") -%>
<%= render 'form' %>

app/views/time_slots/show.html.erb
<%= content_for :title do %>
  <%= @time_slot.name %>
<% end -%>
<%- breadcrum t("time_slots.show.title") -%>
<div class='timeslot-container'>
  <% if @time_slot.get_from_learn %>
    <%= link_to "Ver no Learn", "https://learn.derose.app/admin/in_person_lives/#{@time_slot.get_from_learn["id"]}", style: "margin-bottom: 25px;" %>
  <% else %>
    <%= link_to "Criar no Learn", sync_to_learn_time_slot_path(@time_slot), class: "btn btn-primary", style: "margin-bottom: 25px;" %>
  <% end %>
  <header class='timeslot-head'>
    <legend>
      <%= @time_slot.name %> (<%= @time_slot.start_at.strftime('%H:%M') %> - <%= @time_slot.end_at.strftime('%H:%M') %>)
      <% if @time_slot.cultural_activity -%>
        -
        <%= t('.is_a_cultural_activity') %>
      <% end -%>
    </legend>
  </header>
  <section class=''>
    <p class='timeslot-intructor'><strong><%=TimeSlot.human_attribute_name :padma_uid %></strong>: <%= @time_slot.padma_uid %></p>
    <div class="row">
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to t('edit'), edit_time_slot_path(@time_slot), class: 'btn btn-default btn-xs pull-right' %>
            <%= t('.days_of_the_week') %>
          </div>
          <div class="panel-body">
            <ul class="list-group">
              <% Date::DAYNAMES.each do |dayname| %>
                <%- if @time_slot.send(dayname.downcase.to_sym) %>
                  <li class="list-group-item"><%= dayname %></li>
                <% end -%>
              <% end -%>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to t('edit'), edit_time_slot_path(@time_slot), class: 'btn btn-default btn-xs pull-right' %>
            <%= t('.students') %>
          </div>
          <div class="panel-body">
            <ul class="list-group">
              <% @students.each do |contact| -%>
                <li class="list-group-item"><%= link_to contact.name, "#{APP_CONFIG['crm-url']}/contacts/#{contact.padma_id}" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= t('.regular_participants') %>
          </div>
          <div class="panel-body">
            <ul class="list-group">
              <% @regular_participants.each do |contact| -%>
                <li class="list-group-item"><%= link_to contact.first_name, "#{APP_CONFIG['crm-url']}/contacts/#{contact.id}" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= t('.last_attendances') %>
          </div>
          <div class="panel-body">
              <% @attendances_by_month.each do |month, attendances| %>
                <b><%= I18n.l(month, :format => "%B") %></b>
                <ul class="list-group">
                  <% attendances.each do |att| -%>
                    <li class="list-group-item">
                      <%= I18n.l(att.attendance_on, format: :in_context) %> -
                      
                      <% if att.suspended? %>
                        <span class='results-count-attendances <%= 'attendances0' if att.contacts.count == 0 %>' tabindex='0' data-toggle='popover' data-container='body' data-placement='bottom' data-html='true' data-trigger='focus' data-content='
                        <div class="students-list"> </div>'>
                          <%= t('attendances.index.suspended') %>
                        </span>
                      <% else %>
                        <span class='results-count-attendances <%= 'attendances0' if att.contacts.count == 0 %>' tabindex='0' data-toggle='popover' data-container='body' data-placement='bottom' data-html='true' data-trigger='focus' data-content='
                        <div class="students-list">
                          <%= att.contacts.map{|c| link_to_contact_profile(c)}.join(' ').html_safe %>
                        </div>'>
                          <%= Attendance.human_attribute_name('contacts').capitalize %> (<%= att.contacts.count %>)
                        </span>
                      <% end %>
          
                      - <%= att.username %>
                    </li>
                  <% end %>
                </ul>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <footer class='footer-actions'>
    <%= link_to t('back'), time_slots_path, :class => 'btn btn-link' %>
  </footer>
</div>

app/views/time_slots/vacancies.html.erb
<div class='timeslot-container'>
  <header class='timeslot-head'>
    <legend><%= t('time_slots.index.title') %></legend>
  </header>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= TimeSlot.human_attribute_name(:name) %></th>
        <th><%= TimeSlot.human_attribute_name(:start_at) %></th>
        <th><%= TimeSlot.human_attribute_name(:end_at) %></th>
        <th><%= t('.days') %></th>
        <th><%= t('.vacancies') %></th>
      </tr>
    </thead>
    <tbody>
    <% @time_slots.each do |ts| %>
      <tr>
        <td><%= ts.name %></td>
        <td><%= ts.start_at.strftime('%H:%M') %></td>
        <td><%= ts.end_at.strftime('%H:%M') %></td>
        <td><%= showSchedule ts %></td>
        <td data-text="<%= t('.no_vacancies') %>">
          <%= link_to t('.check_vacancies'), 'javascript:void(0);', onclick: 'checkVacancies(this);', class: 'btn btn-secondary btn-xs' %>
          <%= image_tag 'ajax-loader.gif', id: 'vacancies-think' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>