config/routes.rb
Assistance::Application.routes.draw do

  devise_for :users 
  devise_scope :user do
    get "/login",   to: "sso_sessions#show"
    get '/logout',  to: "sso_sessions#destroy"
    post '/logout', to: "sso_sessions#destroy"
  end
  resource :sso_session

  get "/ping", to: "ping#ping"

  post 'sns', to: 'message_door#sns'
  root 'attendances#index'

  resources :time_slots do
    collection do
      get :vacancies
    end
    member do
      get :sync_to_learn
    end
  end
  resources :attendances
  resources :attendance_contacts, only: [:index]
  get 'attendances_details', to: "attendance_contacts#index"
  resources :trial_lessons
  resources :contacts, :only => [:index, :show, :update]
  resources :stats, :only => [:index] do
    collection do
      get 'attendances_by_teacher', to: "stats#attendances_by_teacher"
      get 'current_month', as: 'current_month', to: 'stats#index', easy_period: :current_month
      get 'last_month', as: 'last_month', to: 'stats#index', easy_period: :last_month
    end
  end

  namespace 'api' do
    namespace 'v0' do
      resource :stats
      resources :merges, only: [:create]
      resources :trial_lessons, only: [:index]
      resources :time_slots, only: [:show, :index]
      resources :attendance_contacts, only: [:create,:destroy]
      resources :contacts, only: [:show, :index] do
        collection do
          post :list, to: 'contacts#index'
        end
        member do
          get :last_trial
          post :sync_from_crm
        end
      end
      resources :imports, only: [:create, :show] do
        member do
          get :failed_rows # GET /api/v0/imports/:id/failed_rows
        end
      end
    end
  end
  

end

app/controllers/api/v0/stats_controller.rb
class Api::V0::StatsController < Api::V0::ApiController

  def show
    @account = Account.find_by_name params[:account_name]
    @stats = InstructorStatsSQLBuilder.new params[:stats].merge({account: @account})
    @contacts = Contact.find_by_sql(@stats.sql)

    if @stats.include_former_students
      @contacts.reject!{|c| c.status == 'former_student' && c.attendance_total == 0 }
    end

    ret = {}
    @contacts.each do |c|
      ret[c.padma_id] = {}
      ret[c.padma_id]["total"] = c.attendance_total.to_i
      @stats.distribution.each do |u|
        ret[c.padma_id][u[:username]] = c.send("sum_#{u[:sql_username]}")/c.attendance_total
      end
    end

    render json: ret

  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  authorize_resource :contact

  before_action :set_defaults, only: [:index] 

  # GET /stats
  def index
  	if params[:distribution] == "instructor"
  		builder_clazz = InstructorStatsSQLBuilder
  	else
  		builder_clazz = TimeSlotStatsSQLBuilder
  	end
    @stats = builder_clazz.new stats_attributes
    
    # @stats.sql already orders by name, but there is a problem in production with latin characters
    # sort_by is needed to correctly sort names with latin characters
    # maybe on postgres update this can be discarded and SQL order used 
    @contacts = Contact.find_by_sql(@stats.sql).sort_by{|c| c.name.parameterize }

    if @stats.include_former_students
      @contacts.reject!{|c| c.status == 'former_student' && c.attendance_total == 0 }
    end

    @teachers = []
    # HASTA RESOLVER PROBLEMA EN UNICORN DE CRM
    #@teachers = CrmLegacyContact.search ids: @contacts.map(&:padma_id),
    #  select: [:local_teacher],
    #  account_name: current_user.current_account.name
    @contacts.in_groups_of(10) do |group|
      @teachers += CrmLegacyContact.search(ids: group.compact.map(&:padma_id),
                                           account_name: current_user.current_account.name)
    end

    @distribution = @stats.distribution
    @distribution_names = @stats.distribution_names
    respond_to do |format|
      format.html
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename="stats.csv"'
      end
    end
  end

  def attendances_by_teacher
    @stats = AttendancesByTeacherStatsSQLBuilder.new stats_attributes
    respond_to do |format|
      format.html
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename="attendances_by_teacher.csv"'
      end
    end
  end

  private

  # default params[:stats] = {}
  # default distribution = instructor
  # default period = current_month
  def set_defaults
  	params[:stats] ||= {}
    if params[:stats] == {}
      params[:easy_period] ||= :current_month
    end

  	params[:distribution] ||= "instructor"
  end

  def stats_attributes
    s = (params[:stats]||{}).merge({:account => current_account})
    case params[:easy_period].try(:to_sym)
      when :current_month
        s.delete_if{|k,_| k =~ /start_on|end_on/ }.merge(start_on: Date.today.beginning_of_month, end_on: Date.today.end_of_month)
      when :last_month
        s.delete_if{|k,_| k =~ /start_on|end_on/ }.merge(start_on: 1.month.ago.beginning_of_month.to_date, end_on: 1.month.ago.end_of_month.to_date)
      else
        s
    end
  end
end

app/helpers/api/v0/stats_helper.rb
module Api::V0::StatsHelper
end

app/helpers/stats_helper.rb
module StatsHelper

  def show_period
    if params[:easy_period]
      l(@stats.start_on, format: :month).capitalize
    else
      "#{l(@stats.start_on, format: :default)} - #{l(@stats.end_on, format: :default)}"
    end
  end

  def active_pill( period )
    if (period.nil? && params[:easy_period].nil?) || (period.try(:to_s) == params[:easy_period].try(:to_s))
      "class=active"
    end
  end
end

app/views/stats/attendances_by_teacher.csv.erb
<%- require 'csv' -%>
<%= CSV.generate(current_user.csv_options.merge((params[:csv_options]||{}).to_hash.symbolize_keys!)) do |csv|
  header = [
      to_current_encoding(t('stats.table.instructor')),
      to_current_encoding(t('stats.attendances_by_teacher.attendances'))
  ]
  csv << header
  
  @stats.result_hash.each_pair do |username, count|
   csv << [username, count]
   csv
  end

end.html_safe %>

app/views/stats/attendances_by_teacher.html.erb
<%- breadcrum t(".attendances") -%>
<div class="container">
  <section>
    <!-- FORM -->
    <div class="row">
      <div class="col">
        <%= link_to "<span class='glyphicon glyphicon-cloud-download'></span> #{t('download')}".html_safe,
          attendances_by_teacher_stats_url(params.merge(format: 'csv')),
          class: 'btn btn-secondary pull-right',
          id: 'download-link' %>
        <%= form_for :stats,
          method: :get,
          url: attendances_by_teacher_stats_url,
          html: {
            class: 'form-horizontal',
            id: 'stats-form',
            data: {
              controller: "easy-period",
              "easy-period-params-period": params[:easy_period]
            }
          } do |f| %>
          <%= hidden_field_tag :easy_period, params[:easy_period], data: {target: "easy-period.field"} %>
          <div id="stats-easy-period" data-target="easy-period.easyPeriodContainer">
            <div class="form-group">
              <%= f.label :easy_period, t('.period'), class: 'control-label col-xs-5 col-md-2' %>
              <div class="col-xs-7 col-md-8 date">
                <ul class="nav nav-pills">
                  <li <%= active_pill "current_month" %> data-target="easy-period.selector" data-selector-value="current_month">
                    <%= link_to t('stats.index.current_month'),
                      "#}",
                      data: {action: "easy-period#setEasyPeriod", "easy-period": "current_month"}
                    %>
                  </li>
                  <li <%= active_pill "last_month" %> data-target="easy-period.selector" data-selector-value="last_month">
                    <%= link_to t('stats.index.last_month'),
                      "#",
                      data: {action: "easy-period#setEasyPeriod", "easy-period": "last_month"}
                    %>
                  </li>
                  <li <%= active_pill "" %> data-target="easy-period.selector" data-selector-value="custom">
                    <%= link_to t('stats.index.custom_period'),
                      "#",
                      data: {action: "easy-period#setEasyPeriod", "easy-period": "custom"} %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div id="stats-custom-period" data-target="easy-period.customPeriodContainer">
            <div class="form-group">
              <%= f.label :start_on,t('activerecord.attributes.stat.start_on'), :class => 'control-label col-xs-5 col-md-2' %>
              <div class='col-xs-7 col-md-8'>
                <div class="input-group date">
                  <%= f.date_select :start_on, {},{:class => 'form-control', disabled: true} %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :end_on,t('activerecord.attributes.stat.end_on'), :class => 'control-label col-xs-5 col-md-2' %>
              <div class='col-xs-7 col-md-8'>
                <div class="input-group date">
                  <%= f.date_select :end_on, {},{:class => 'form-control', disabled: true} %>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class='col-xs-5 col-md-2'></div>
            <div class='col-xs-7 col-md-8 checkbox'>
              <%= f.check_box :include_cultural_activities %> <%= f.label :include_cultural_activities,t('activerecord.attributes.stat.include_cultural_activities'), :class => '' %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-xs-5 col-md-2"></div>
            <div class='col-xs-7 col-md-8'>
              <%= f.submit t('stats.index.calculate_stats'), :class => 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <!-- RESULT -->
    <div class="row">
      <div class="col">
        <table class="table table-striped table-bordered table-hover table-condensed sticky-header">
          <thead>
          <tr>
            <th><%= t('stats.table.instructor') %></th>
            <th><%= t(".attendances") %></th>
          </tr>

          </thead>
          <tbody>
            <% @stats.result_hash.each_pair do |username, count| %>
              <tr>
                <td><%= username %></td>
                <td><%= count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


  </section>
</div>

app/views/stats/index.csv.erb
<%- require 'csv' -%>
<%= CSV.generate(current_user.csv_options.merge((params[:csv_options]||{}).to_hash.symbolize_keys!)) do |csv|
  header = [
      to_current_encoding(t('stats.table.name')),
      to_current_encoding(t('stats.table.instructor')),
      to_current_encoding(t('stats.table.total'))
  ]

  @distribution_names.each do |name|
    header << to_current_encoding(name)
    header << to_current_encoding(name)
  end
  csv << header
  
  @contacts.each do |c|
    dist_array = []

    dist_array << to_current_encoding(c.name)
    dist_array << to_current_encoding(
      User.full_name_for(@teachers.select{ |pc| pc.id == c.padma_id }.first.try :local_teacher))
    dist_array << to_current_encoding(number_with_precision(c.attendance_total || 0, 
                                                            precision: 0))
    
    @distribution.each do |d|
        sum_method = d.is_a?(Hash)? "sum_#{d[:sql_username]}" : "sum_#{d}"
  	  	dist_array << to_current_encoding(number_with_precision(c.send(sum_method), 
                                                                precision: 0))

        attendance_average = 0
        if c.attendance_total > 0
          attendance_average = c.send(sum_method)/c.attendance_total.to_f*100
        end

  	  	dist_array << to_current_encoding(
          number_to_percentage(
            attendance_average,
            :precision => 2,
            :strip_insignificant_zeros => true
          ).to_s
        )
    end

    csv << dist_array
  end

end.html_safe %>

app/views/stats/index.html.erb
<%- breadcrum t("stats.index.title") -%>
<div class='stats-container'>
  <div class="alert alert-info">
    <p>
      No <b>Learn DeROSE</b> você acha um reporte equivalente a este mas calculado com os check-ins. Pode ver <%= link_to "Você pode encontrá-lo aqui", "https://learn.derose.app/admin/check_ins_distribution_report", target: "_blank" %>.
      <br>
      Recomendamos você passar a usar os check-ins do Learn no lugar das presenças. Fica bem mais prático! e você tem mais opções no relatório. Da para incluir ou não check-ins em videos, ver participação de seus alunos em aulas ou conteúdos de outras escolas e muito mais!
      <br>
      Você pode fazer pode fazer chamada de forma rápida com o app do Instrutor do Learn ou ainda melhor, ter os check-ins cadastrados de forma AUTOMÁTICA 😃. <%= link_to "Veja mais aquí", "https://deroseapp.notion.site/Check-ins-Presen-as-aprimoradas-e0175e32433149d88ba6aa8e475a581a", target: "_blank" %>
    </p>
  </div>
  <header class='stats-head'><%= show_period %></header>
  <section class='stats-content clearfix'>
    <div class='col-xs-12 col-md-12'>
      <%= link_to "<span class='glyphicon glyphicon-cloud-download'></span> #{t('download')}".html_safe, stats_url(params.merge(format: 'csv')), class: 'btn btn-secondary pull-right', id: 'download-link', data: {turbolinks: false} %>
      <%= form_for :stats, method: :get, url: stats_path, html: { class: 'form-horizontal', id: 'stats-form' } do |f| %>
        <div id="stats-easy-period">
          <div class="form-group">
            <%= f.label :easy_period, t('.period'), :class => 'control-label col-xs-5 col-md-2' %>
            <div class="col-xs-7 col-md-8 date">
              <ul class="nav nav-pills">
                <li <%= active_pill :current_month %>><%= link_to t('.current_month'), '#', id: 'open-current-month' %></li>
                <li <%= active_pill :last_month %>><%= link_to t('.last_month'), '#', id: 'open-last-month' %></li>
                <li <%= active_pill nil %>><%= link_to t('.custom_period'), '#', id: 'show-custom-period' %></li>
              </ul>
            </div>
          </div>
        </div>
        <div id="stats-custom-period">
          <div class="form-group">
            <%= f.label :start_on,t('activerecord.attributes.stat.start_on'), :class => 'control-label col-xs-5 col-md-2' %>
            <div class='col-xs-7 col-md-8'>
              <div class="input-group date">
                <%= f.date_select :start_on, {},{:class => 'form-control', disabled: true} %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :end_on,t('activerecord.attributes.stat.end_on'), :class => 'control-label col-xs-5 col-md-2' %>
            <div class='col-xs-7 col-md-8'>
              <div class="input-group date">
                <%= f.date_select :end_on, {},{:class => 'form-control', disabled: true} %>
              </div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :distribution,t('activerecord.attributes.stat.distribution'), :class => 'control-label col-xs-5 col-md-2' %>
          <div class='col-xs-7 col-md-8'>
            <div class='select'>
              <%= select_tag :distribution, options_for_select({t('stats.index.by_instructor') => :instructor, t('stats.index.by_time_slot') => :time_slot}, params[:distribution]), {:class => 'form-control'} %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class='col-xs-5 col-md-2'></div>
          <div class='col-xs-7 col-md-8 checkbox'>
            <%= f.check_box :include_cultural_activities %> <%= f.label :include_cultural_activities,t('activerecord.attributes.stat.include_cultural_activities'), :class => '' %>
          </div>
        </div>

        <% if can?(:include_former_students, :stats) -%>
          <div class="form-group">
            <div class='col-xs-5 col-md-2'></div>
            <div class='col-xs-7 col-md-8 checkbox'>
              <%= f.check_box :include_former_students %> <%= f.label :include_former_students, t('activerecord.attributes.stat.include_former_students'), :class => '' %>
            </div>
          </div>
        <% end -%>

        <div class="form-group">
          <div class='col-xs-5 col-md-2'></div>
          <div class='col-xs-7 col-md-8 checkbox'>
            <%= f.check_box :include_former_teachers %> <%= f.label :include_former_teachers, t('activerecord.attributes.stat.include_former_teachers'), :class => '' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-xs-5 col-md-2"></div>
          <div class='col-xs-7 col-md-8'>
            <%= f.submit t('stats.index.calculate_stats'), :class => 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
    <table class="table table-striped table-bordered table-hover table-condensed sticky-header">
      <thead>
      	<tr>
      	  <th><%= t('stats.table.name')%></th>
          <th><%= t('stats.table.instructor') %></th>
      	  <th><%= t('stats.table.total')%></th>
      	  <% @distribution_names.each do |name| %>
      	  	<th colspan="2"><%= User.full_name_for(name) %></th>
      	  <% end %>
      	</tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
        	<tr>
        	  <td><%= link_to contact.name, contact_path(:id => contact.padma_id) %></td>
            <td><%= User.full_name_for(@teachers.detect{ |c| c.id == contact.padma_id }.try :local_teacher) %></td>
        	  <td><%= number_with_precision(contact.attendance_total || 0, precision: 0) %></td>
            <% @distribution.each do |u| %>
              <% sum_method = u.is_a?(Hash) ? "sum_#{u[:sql_username]}" : "sum_#{u}" %>
        	  	<td><%= number_with_precision contact.send(sum_method), precision: 0 %></td>
        	  	<td><%= number_to_percentage contact.attendance_total > 0 ? contact.send(sum_method)/contact.attendance_total.to_f*100 : 0, :precision => 2, :strip_insignificant_zeros => true %></td>
        	  <% end %>
        	</tr>
        <% end %>
      </tbody>
    </table>

    <div class="row">
      <div class='col-xs-8 col-md-8'>
      </div>
      <div class='col-xs-4 col-md-4 text-right'>
        <%= link_to t(".attendances_detail"), attendance_contacts_path(format: :csv) %>
      </div>
    </div>

  </section>
</div>