config/routes.rb
Assistance::Application.routes.draw do

  devise_for :users 
  devise_scope :user do
    get "/login",   to: "sso_sessions#show"
    get '/logout',  to: "sso_sessions#destroy"
    post '/logout', to: "sso_sessions#destroy"
  end
  resource :sso_session

  get "/ping", to: "ping#ping"

  post 'sns', to: 'message_door#sns'
  root 'attendances#index'

  resources :time_slots do
    collection do
      get :vacancies
    end
    member do
      get :sync_to_learn
    end
  end
  resources :attendances
  resources :attendance_contacts, only: [:index]
  get 'attendances_details', to: "attendance_contacts#index"
  resources :trial_lessons
  resources :contacts, :only => [:index, :show, :update]
  resources :stats, :only => [:index] do
    collection do
      get 'attendances_by_teacher', to: "stats#attendances_by_teacher"
      get 'current_month', as: 'current_month', to: 'stats#index', easy_period: :current_month
      get 'last_month', as: 'last_month', to: 'stats#index', easy_period: :last_month
    end
  end

  namespace 'api' do
    namespace 'v0' do
      resource :stats
      resources :merges, only: [:create]
      resources :trial_lessons, only: [:index]
      resources :time_slots, only: [:show, :index]
      resources :attendance_contacts, only: [:create,:destroy]
      resources :contacts, only: [:show, :index] do
        collection do
          post :list, to: 'contacts#index'
        end
        member do
          get :last_trial
          post :sync_from_crm
        end
      end
      resources :imports, only: [:create, :show] do
        member do
          get :failed_rows # GET /api/v0/imports/:id/failed_rows
        end
      end
    end
  end
  

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :account
  belongs_to :time_slot

  has_many :attendance_contacts, inverse_of: :attendance
  has_many :contacts, through: :attendance_contacts, dependent: :destroy

  validates :account, presence: true
  validates :time_slot, presence: true
  validates :attendance_on, presence: true
  validates :username, presence: true
  validates_date :attendance_on, on_or_before: :today
  validate :only_on_per_day_per_slot
  validate :no_duplicate_contact_ids

  attr_accessor :padma_contacts

  #attr_accessible :account_id, :time_slot_id, :attendance_on, :padma_contacts, :username, :suspended

  accepts_nested_attributes_for :attendance_contacts

  before_validation :set_default_username

  def trial_lessons
    TrialLesson.where(time_slot_id: self.time_slot_id, trial_on: self.attendance_on)
  end

  def padma_contacts= padma_contacts
    return if time_slot.nil?
    contact_ids = []
    padma_contacts.uniq.each do |padma_contact_id|
      contact = Contact.get_by_padma_id(padma_contact_id, account_id || time_slot.account_id)
      contact_ids << contact.id
    end
    self.contact_ids = contact_ids
  end

  def set_default_username
    update_attribute(:username, time_slot.padma_uid) unless username.present? or time_slot.blank?
  end
  private

  def only_on_per_day_per_slot
    if Attendance.where(account_id: self.account_id,
                        time_slot_id: self.time_slot_id,
                        attendance_on: self.attendance_on).count > ((self.persisted?)? 1 : 0)
      errors.add(:attendance_on, :already_registered)
    end
  end

  def no_duplicate_contact_ids
    if contact_ids.uniq.length != contact_ids.length
      errors.add(:contacts, :duplicated)
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :load_attendance, only: [:create, :update, :new]
  load_and_authorize_resource

  rescue_from ActionController::InvalidAuthenticityToken, with: :handle_invalid_authenticity_token

  def index
    @day_span = 7

    @days_from = params[:days_from] || 0
    @days_to = params[:days_to] || @day_span
    further_limit = @days_to.to_i
    closer_limit = @days_from.to_i
    @view_range = (further_limit - 1).downto(closer_limit)
    @attendances = @attendances.where(attendance_on: (further_limit.days.ago.to_date..closer_limit.days.ago.to_date))

    @time_slots = current_user.current_account.time_slots.reorder(:start_at)

    unless params[:username].nil?
      cookies[:filter_attendances_by_username] = params[:username]
    end
    @username = params[:username] || cookies[:filter_attendances_by_username]

    @time_slots = @time_slots.where(padma_uid: @username) if @username.present?
    @only_pending =  ActiveRecord::Type::Boolean.new.type_cast_from_database(params[:only_pending])
    @time_slots_wout_day = current_user.current_account.time_slots.without_schedule

    @recent = nil # disable until bug #107776460 fixed
    # @recent = get_recent_time_slot
    
    respond_to do |format|
      format.html
    end
  end

  def new
    @remote_form = true
    @back_w_params = params.select{|k,v| k.in?(%W(days_to days_from only_pending username))}
    @time_slot = @attendance.time_slot
    unless @time_slot.nil?
      @attendance.username = @time_slot.padma_uid # default attendance teacher to timeslot teacher
      @padma_contacts = @time_slot.recurrent_contacts
      @trial_lessons = TrialLesson.where(time_slot_id: @attendance.time_slot_id, trial_on: @attendance.attendance_on)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @remote_form = true
    @padma_contacts = @attendance.time_slot.recurrent_contacts
    @trial_lessons = TrialLesson.where(time_slot_id: @attendance.time_slot_id, trial_on: @attendance.attendance_on)
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def show
    @trial_lessons = @attendance.trial_lessons

    respond_to do |format|
      format.html
    end
  end

  def create
    back_w_params = ActiveSupport::JSON.decode(params[:redirect_back_w_params]) if params[:redirect_back_w_params]
    update_trial_lessons @attendance, params[:trial_lessons], :create
    
    if @attendance.save
      @padma_contacts = @attendance.time_slot.recurrent_contacts
      respond_to do |format|
        format.html { redirect_to attendances_url(back_w_params) }
        format.js { render 'update' }
      end
    else
      respond_to do |format|
        flash.now[:alert] = "#{clean_errors(@attendance.errors)}"
        format.js { render 'update' }
      end
    end
  end

  def update
    update_trial_lessons @attendance, params[:trial_lessons], :update
    if @attendance.update(attendance_params_for_update)
      respond_to do |format|
       format.html { redirect_to attendances_url }
       format.json { render json: {id: @attendance.id, message: "updated"}, status: 201 }
       format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "#{clean_errors(@attendance.errors)}"
        format.js { render 'update' }
      end
    end
  end

  def destroy
    update_trial_lessons @attendance, params[:trial_lessons], :destroy
    contacts = @attendance.contacts.map(&:id)
    account = @attendance.account
    @attendance.destroy
    Contact.find(contacts).map{|c| c.update_last_seen_at(account)}

    redirect_to attendances_path
  end
  
  private

  def handle_invalid_authenticity_token
    Rails.logger.error "InvalidAuthenticityToken error raised"
    Rails.logger.error "CSRF token: #{form_authenticity_token}"
    Rails.logger.error "Session CSRF Token: #{session[:_csrf_token]}"

    redirect_back fallback_location: root_path, alert: "Something went wrong. Please try again"
  end

  def attendance_params_for_update
    permitted_params = attendance_params
    if params[:attendance] && params[:attendance][:padma_contacts].nil?
      permitted_params = permitted_params.merge!({padma_contacts: []})
    end
    permitted_params
  end

  def get_recent_time_slot
    recent = current_user.current_account.time_slots # Get all account timeslots
	    .where(padma_uid: current_user.username) # for current user
	    .where("#{Time.now.strftime('%A').downcase}".to_sym => true) # That ocurr today
	    .select {|t|
	      # Select those that already started 
	      Time.zone.local(Time.zone.now.year, Time.zone.now.month, Time.zone.now.day, t.start_at.hour, t.start_at.min) <= Time.zone.now and
	      # And that finished (or not) 1/2 hour ago
	      Time.zone.now <= (Time.zone.local(Time.zone.now.year, Time.zone.now.month, Time.zone.now.day, t.end_at.hour, t.end_at.min) + 30.minutes)
    }.last # Get the last one

    # If there is an attendance already set for the recent timeslot dont show it
    if recent.present?
      if Attendance.where(time_slot_id: recent.id, attendance_on: Time.zone.today).exists?
        nil
      else
        recent
      end
    end
  end
  
  def update_trial_lessons attendance, trial_lesson_ids, action

    unless trial_lesson_ids.nil?
      trial_lesson_ids.each do |id|
        tl = TrialLesson.where(:account_id => current_user.current_account.id).find(id)
        tl.inform_crm(action, I18n.locale, true)
        tl.update_attribute(:assisted, true)
      end
    end

    unless attendance.trial_lessons.empty?
      not_attended = attendance.trial_lessons.pluck(:id) - ( trial_lesson_ids.try(:map,&:to_i) || [] )
      not_attended.each do |id|
        tl = TrialLesson.where(:account_id => current_user.current_account.id).find(id)
        tl.inform_crm(action, I18n.locale, false)
      end
    end
  end

  def clean_errors(error_hash)
    e = ""
    error_hash.each do |k,v|
      e << "," unless e.blank?
      e << "#{k}: #{v}"
    end
    e
  end

  def load_attendance
    if params.has_key?(:id)
      @attendance = Attendance.find(params[:id])
      @attendance.account_id = current_user.current_account.id
    else
      @attendance = Attendance.new(attendance_params)
      @attendance.account_id = current_user.current_account.id
    end
  end

  def attendance_params
    params.require(:attendance).permit(
        :account_id,
        :time_slot_id,
        :attendance_on,
        :username,
        :suspended,
        :padma_contacts => []
    )
  end

end

app/helpers/attendances_helper.rb
require 'weeks_in_month'
module AttendancesHelper
  include WeeksInMonth

  def future_lesson?(date,time_slot)
	  lesson_time = Time.zone.local(date.year, date.month, date.day, time_slot.start_at.hour, time_slot.start_at.min) >= Time.zone.now
  end

  def keep_params
    params.select{|k,v| k.in?(%W(days_to days_from only_pending username))}
  end

  def keep_params_hidden_tag
    hidden_field_tag :redirect_back_w_params, @back_w_params.to_json
  end

  def render_time_slot?(time_slot,date,att, only_pending)
    (att.present? && !only_pending) || (att.blank? && time_slot.send(Date::DAYNAMES[date.wday].downcase.to_sym) )
  end

  def timeslot_description(timeslot, attendance=nil)
    "#{timeslot_period(timeslot)} (#{attendance.present? ? User.full_name_for(attendance.username) : User.full_name_for(timeslot.padma_uid)})"
  end

  def timeslot_period(timeslot)
    "#{timeslot.start_at.hour}:#{minutes(timeslot.start_at)}-#{timeslot.end_at.hour}:#{minutes(timeslot.end_at)}"
  end

  def time_slot_attendace_html_id(time_slot,date)
    "time_slot_#{time_slot.id}_date_#{date.strftime('%d%m%y')}"
  end

  private

  def minutes(datetime)
    m = datetime.min
    if m < 10
      "0#{m}"
    else
      m
    end
  end

end

app/views/attendances/_filters_explanation.html.erb
<div class='attendance-filter-list margin-bottom-20 <%= "hide" unless @username.present? or @only_pending.present?%>'> <!-- show when active filters -->
  <label class='label-filter'><%= t('attendances.index.enabled_filters') %>:</label>
  <% if @only_pending.present? %>
    <div class='label label-success'><%= t('attendances.index.filters.pending') %><%= link_to '&times;'.html_safe, attendances_path(username: @username, days_from: @days_from.to_i - @day_span, days_to: @days_to.to_i - @day_span), class: 'close' %></div>
  <% end %>
  <% if @username.present? %>
    <div class='label label-success'><%= @username %> <%= link_to '&times;'.html_safe, attendances_path(only_pending: @only_pending, days_from: @days_from.to_i - @day_span, days_to: @days_to.to_i - @day_span), class: 'close' %></div>
  <% end %>
</div>

app/views/attendances/_form.html.erb
<div class="row" id="attendance">
  <div class="col-md-6 col-sm-12 col-xs-12">
    <%= form_for @attendance, :html => { :class => 'form-horizontal' } do |f| %>
      <div class='well'>
        <% if @attendance.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

            <ul>
            <% @attendance.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <fieldset>
          <% if  @attendance.attendance_on and  @attendance.time_slot %>
            <legend>
              <%= t('activerecord.attributes.attendance.attendance_to') %> "<%= @attendance.time_slot.name %>"<br/>
              <%= t('activerecord.attributes.attendance.text_on') %> <%= l @attendance.attendance_on, format: :long %>
            </legend>
            <div class="hidden"><%= f.date_select :attendance_on, :default => Time.zone.today %></div>
            <%= f.hidden_field :time_slot_id %>
          <% else %>
            <legend><%= t('activerecord.attributes.attendance.attendance_to') %></legend>
            <div class='form-group'>
              <%= f.label :attendance_on, :class => 'control-label col-xs-5 col-md-4' %>
              <div class="col-xs-7 col-md-8">
                <div class='input-group date'>
                  <%= f.date_select :attendance_on, {:default => Time.zone.today}, {:class => "form-control"} %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :time_slot_id, :class => 'control-label col-xs-5 col-md-4' %>
              <div class="col-xs-7 col-md-8">
                <div class='select'>
  		            <%= f.collection_select :time_slot_id, current_user.current_account.time_slots, :id, :name, {:prompt => t('attendances.form.select_timeslot')},{:class => 'selectpicker select_width show-tick show-menu-arrow form-control'} %>
                </div>
              </div>
            </div>
          <% end %>
          <% unless @trial_lessons.blank? %>
            <div class="form-group">
              <%= f.label :trial_lessons, :class => 'control-label col-xs-5 col-md-4' %>
              <div class="col-xs-7 col-md-8">
                <div class="row" id="trial_lessons">
                  <% @trial_lessons.each_with_index do |tl, index| %>
                    <div class="checkbox col-sm-10">
                      <%= check_box_tag "trial_lessons[]", tl.id, tl.assisted?, class: "trial_lessons", id: "trial_lessons_#{index}" %> <%= label_tag "trial_lessons[]", "#{t('attendances.form.contact_assisted', name: tl.contact.name)}"%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        	<div class="">
            <%= f.label :padma_contacts, :class => 'col-xs-12 col-md-12' %>
          </div>
        </fieldset>
        <ul id="attendance_contacts" class='list-unstyled'>
          <% @attendance.contacts.each do |c| %>
            <li>
              <%= hidden_field_tag "attendance[padma_contacts][]", c.padma_id %>
              <%= link_to "#{c.name}", "#", class: "delete btn btn-default btn-sm btn-block" %>
            </li>
          <% end %>
        </ul>
        <div class='text-center'>
          <div class='select'>
            <%= select_tag :padma_contacts_select, options_for_select({t('attendances.form.recurrents_contacts') => :recurrent_contacts, t('attendances.form.all_contacts') => :all_students}.merge(Hash[current_user.current_account.usernames.map {|username| [t('attendances.form.students_of', teacher: User.full_name_for(username)), username].flatten}]) ), {:class => 'selectpicker show-tick show-menu-arrow form-control'} %>
          </div>
          <span id="loader"><%= image_tag("ajax-loader.gif") %></span>
        </div>
        <fieldset id="attendance_padma_contacts">
          <%= render :partial => 'shared/padma_contacts' %>
        </fieldset>
        <footer class="form-footer margin-top-10">
          <%= f.submit nil, :class => 'btn btn-primary' %>
          <%  if @attendance.persisted?  -%>
            <%= link_to t('Show'), @attendance, :class => 'btn btn-secondary'%>
            <%= link_to t('destroy'), @attendance, :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
          <% end -%>
            <%= link_to t('Cancel'), attendances_path, :class => 'btn btn-link' %>
        </footer>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/_modal_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title"><%= t('attendances.index.new') %></h4>
    </div>
    <% format = (@remote_form)? 'js' : 'html' -%>
    <%= form_for @attendance, remote: @remote_form, format: format, html: { class: 'checkattendance-form', role: 'form'} do |f| %>
      <div class="modal-body">
        <%= keep_params_hidden_tag %>

        <div class='form-group'>
          <%= f.label :attendance_on, :class => 'control-label' %>
          <div class='input-group date'>
            <%= f.date_select :attendance_on, {:default => Time.zone.today}, {:class => "form-control"} %>
          </div>
          <%= f.label :time_slot_id, :class => 'control-label' %>
          <div class='select'>
            <%= f.collection_select :time_slot_id, current_user.current_account.time_slots.order("name"), :id, :description_with_day, {:prompt => t('attendances.form.select_timeslot')}, {:class => 'form-control', :id => 'time_slot_modal_form'} %>
          </div>
        </div>

        <div class='form-group'>
          <label class='control-label'><%= t('attendances.form.username') %></label>
          <div class='select'>
            <%= f.select :username,
              options_for_select(
                current_user.current_account.usernames.map{|u| [User.full_name_for(u),u]},
                :selected => @attendance.username || current_user.username),
                {
                  :prompt => t('attendances.form.select_username')
                },
                {
                  :class => 'form-control'
                } %>
          </div>
        </div>

        <% unless @trial_lessons.blank? %>
          <div class="form-group">
            <%= f.label :trial_lessons, :class => 'control-label' %>
            <% @trial_lessons.each_with_index do |tl, index| %>
              <div class="checkbox">
                <%= check_box_tag "trial_lessons[]", tl.id, tl.assisted?, class: "trial_lessons", id: "trial_lessons_#{index}" %> <%= label_tag "trial_lessons[]", "#{t('attendances.form.contact_assisted', name: tl.contact.name)}"%>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class='form-group'>
          <%= f.label :padma_contacts, "#{t('attendances.form.participants')}:", :class => 'control-label' %>
          <ul id="attendance_contacts" class='list-unstyled'>
            <% @attendance.contacts.each do |c| %>
              <li>
                <%= hidden_field_tag "attendance[padma_contacts][]", c.padma_id %>
                <%= link_to "#{c.name}", "#", class: "delete btn btn-default btn-sm btn-block" %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class='form-group'>
          <label class='control-label'><%= t('attendances.form.select_contacts') %>:</label>
          <div class='select'>
            <%= select_tag :padma_contacts_select, options_for_select({t('attendances.form.recurrents_contacts') => :recurrent_contacts, t('attendances.form.all_contacts') => :all_students}.merge(Hash[current_user.current_account.usernames.map {|username| [t('attendances.form.students_of', teacher: User.full_name_for(username)), username].flatten}]) ), {:class => 'form-control'} %>
          </div>
          <span id="loader"><%= image_tag("ajax-loader.gif") %></span>
        </div>

        <fieldset id="attendance_padma_contacts">
          <%= render :partial => 'shared/padma_contacts' %>
        </fieldset>
      </div>
      <footer class="modal-footer">
        <button id="cancel-attendance" type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('cancel') %></button>
        <%= f.submit t('attendances.form.save_attendance'), data: { 'disable-with' => '...' }, class: "submit-attendance btn btn-primary", style: ('display: none' if @attendance.contacts.count == 0)%>
        <%= f.submit t('attendances.form.save_empty'), data: { 'disable-with' => '...' }, class: "submit-attendance btn btn-danger", style: ('display: none' if @attendance.contacts.count > 0)%>
      </footer>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  TrialLessonSelect.setup('#time_slot_modal_form');

  <% if @remote_form -%>
    $("form.checkattendance-form").on("ajax:complete",function(){
      $(".modal").modal("hide");
    }).on("ajax:error",function(){
    }).on("ajax:success",function(){
    });
  <% end -%>
</script>

app/views/attendances/_new_recent_attendance.html.erb
<div class='filter-controls filter-controls-right'>
	<% if @recent.present? %>
	  <div class='recent-time-slot'>
	    <span class='label-filter'><%= t('attendances.index.recent_time_slot') %>: <%= @recent.name %></span>
	  </div>
	  <%= link_to t('attendances.index.new'), new_attendance_path(keep_params.merge({attendance: {attendance_on: Time.zone.now.to_date, time_slot_id: @recent.id}})), {remote: true, data: {toggle: 'modal', target: '#dialog-check-attendance'}, class: 'btn btn-primary', id: 'recent-call-to-action' } %>
	  <%= link_to t('attendances.index.new_empty'), attendances_path({redirect_back_w_params: keep_params.to_json}.merge({attendance: {attendance_on: Time.zone.now.to_date, time_slot_id: @recent.id}})), confirm: t('confirm'), method: :post, class: 'btn btn-danger empty_attendance', id: 'empty-recent-call-to-action' %>
	<% else -%>
	  <%= link_to t('attendances.index.new'), new_attendance_path(keep_params.merge({attendance: {attendance_on: Time.zone.now.to_date}})), {remote: true, data: {toggle: 'modal', target: '#dialog-check-attendance'}, class: 'btn btn-primary', id: 'generic-call-to-action' } %>
	<% end %>
</div>

app/views/attendances/_time_slot.html.erb
<% att = @attendances.select {|a| a.attendance_on == date && a.time_slot == time_slot}.first %>
<% if render_time_slot?(time_slot,date,att, only_pending) -%>
  <li class="list-group-item <%= 'today' if date.today? %> <%= 'pending' if !only_pending && att.blank? && !future_lesson?(date,time_slot) %> <%= 'future-lesson' if future_lesson?(date,time_slot) %>" <%= 'future-lesson' if att.try(:suspended?) %>>
    <header class='timeslot-head'><%= link_to time_slot.name, time_slot %></header>
    <div class='timeslot-content' data-controller="popover">
      <div class='timeslot-description'>
        <p><%= timeslot_description(time_slot, att) %></p>
        <% if att %>
          <% if att.suspended? %>
            <span class='results-count-attendances <%= 'attendances0' if att.contacts.count == 0 %>' data-target="popover.container" tabindex='0' data-toggle='popover' data-container='body' data-placement='bottom' data-html='true' data-trigger='focus' data-content='
            <div class="students-list"> </div>
            <div class="clearfix popover-footer students-list-footer">
              <%= link_to t('attendances.index.destroy'), att, :method => :delete, data: { confirm: t('confirm') }, :class => 'btn btn-xs btn-block' %>
            </div>'>
              <%= t('attendances.index.suspended') %>
            </span>
          <% else %>
            <span class='results-count-attendances <%= 'attendances0' if att.contacts.count == 0 %>' tabindex='0' data-target="popover.container" data-toggle='popover' data-trigger='manual' data-container='body' data-placement='bottom' data-html='true' data-trigger='focus' data-content='
            <div class="students-list">
              <%= att.contacts.map{|c| link_to_contact_profile(c)}.join(' ').html_safe %>
            </div>
            <div class="clearfix popover-footer students-list-footer">
              <%= link_to t('attendances.index.edit'), edit_attendance_path(att), {remote: true, data: {toggle: 'modal', target: '#dialog-check-attendance'}, :class => "btn btn-xs pull-right popover-edit"} %>
              <%= link_to t('attendances.index.destroy'), att, :method => :delete, data: { confirm: t('confirm') }, :class => 'btn btn-xs pull-left' %>
            </div>'>
              <%= Attendance.human_attribute_name('contacts').capitalize %> (<%= att.contacts.count %>)
            </span>
          <% end %>
        <% end %>
      </div>
      <% if !att %>
        <div class='timeslot-controls'>
          <%= link_to t('attendances.index.new'), new_attendance_path(keep_params.merge({attendance: {attendance_on: date, time_slot_id: time_slot.id}})), {remote: true, data: {toggle: 'modal', target: '#dialog-check-attendance'}, class: 'btn btn-primary btn-xs btn-block initialized_attendance' } %>
          <%= link_to t('attendances.index.new_empty'), attendances_path({redirect_back_w_params: keep_params.to_json}.merge({attendance: {attendance_on: date, time_slot_id: time_slot.id}, format: :js})), data: {confirm: t('confirm')}, method: :post, remote: true, class: 'btn btn-danger btn-xs btn-block empty_attendance' %>
          <%= link_to t('attendances.index.suspended'), attendances_path({redirect_back_w_params: keep_params.to_json}.merge({attendance: {attendance_on: date, time_slot_id: time_slot.id, suspended: true}, format: :js})), data: {confirm: t('confirm')}, method: :post, remote: true, class: 'btn btn-link btn-xs btn-block empty_attendance' %>
        </div>
      <% end %>
    </div>
  </li>
<% end %>

app/views/attendances/_warn_unscheduled_timeslots.html.erb
<% unless @time_slots_wout_day.empty? -%>
  <div class="alert alert-warning">
    <p><%= t('.timeslots_wout_schedule_warning') %></p>
    <ul class="list-group">
      <% @time_slots_wout_day.each do |time_slot| -%>
        <li class="list-group-item">
	  <b><%= time_slot.name %></b> <%= timeslot_description(time_slot, nil) %> <%= link_to t('attendances.index.edit'), edit_time_slot_path(time_slot), :class => 'btn btn-default btn-xs' %> <%= link_to t('attendances.index.ignore'), time_slot_path(time_slot), :class => 'btn btn-default btn-xs ignore_unscheduled' %>
        </li>
      <% end -%>
    </ul>
  </div>
<% end -%>

app/views/attendances/show.html.erb
<%- breadcrum t("attendances.show.title") -%>

<p id="notice"><%= notice %></p>


<p>
  <b><%=Attendance.human_attribute_name :attendance_on %></b><br>
  <%= @attendance.attendance_on %>
</p>

<p>
  <b><%=Attendance.human_attribute_name :time_slot %></b><br>
  <%= @attendance.time_slot.name %>
</p>

<p>
  <b><%= t('.teacher_on_this_attendace') %></b><br>
  <%= @attendance.username %>
</p>

<b><%= Attendance.human_attribute_name :trial_lessons %></b><br>
<ul>
	<% @trial_lessons.each do |tl| %>
	  <li>
      <% if tl.contact.nil? %>
        <div class="alert alert-warning" role="alert">
          <%= t('attendances.show.trial_lesson_without_contact') %>
        </div>
      <% else %>
        <%= tl.contact.name %>
        <%= content_tag :span, t(".Assisted"), :class => "label label-success" if tl.assisted? %>
        <%= content_tag :span, t(".Absent"), :class => "label label-important" unless tl.assisted? %>
      <% end %>
	  </li>	
	<% end %>
</ul>

<b><%=Attendance.human_attribute_name :contacts %></b><br>	
<ul>
	<% @attendance.contacts.each do |c| %>
	  <li><%= c.name %></li>	
	<% end %>
</ul>

<%= link_to t('edit'), edit_attendance_path(@attendance), {remote: true, data: {toggle: 'modal', target: '#dialog-check-attendance'}, :class => "btn btn-primary"} %>
<%= link_to t('destroy'), @attendance, :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>

<div class="modal fade modal-fixed-footer" id='dialog-check-attendance'>
</div>