config/routes.rb
Assistance::Application.routes.draw do

  devise_for :users 
  devise_scope :user do
    get "/login",   to: "sso_sessions#show"
    get '/logout',  to: "sso_sessions#destroy"
    post '/logout', to: "sso_sessions#destroy"
  end
  resource :sso_session

  get "/ping", to: "ping#ping"

  post 'sns', to: 'message_door#sns'
  root 'attendances#index'

  resources :time_slots do
    collection do
      get :vacancies
    end
    member do
      get :sync_to_learn
    end
  end
  resources :attendances
  resources :attendance_contacts, only: [:index]
  get 'attendances_details', to: "attendance_contacts#index"
  resources :trial_lessons
  resources :contacts, :only => [:index, :show, :update]
  resources :stats, :only => [:index] do
    collection do
      get 'attendances_by_teacher', to: "stats#attendances_by_teacher"
      get 'current_month', as: 'current_month', to: 'stats#index', easy_period: :current_month
      get 'last_month', as: 'last_month', to: 'stats#index', easy_period: :last_month
    end
  end

  namespace 'api' do
    namespace 'v0' do
      resource :stats
      resources :merges, only: [:create]
      resources :trial_lessons, only: [:index]
      resources :time_slots, only: [:show, :index]
      resources :attendance_contacts, only: [:create,:destroy]
      resources :contacts, only: [:show, :index] do
        collection do
          post :list, to: 'contacts#index'
        end
        member do
          get :last_trial
          post :sync_from_crm
        end
      end
      resources :imports, only: [:create, :show] do
        member do
          get :failed_rows # GET /api/v0/imports/:id/failed_rows
        end
      end
    end
  end
  

end

app/views/layouts/_flash_messages.html.erb
<% if flash.present? %>
  <% if !flash.notice.blank? %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.notice %>
    </div>
  <% end %>
  <% if !flash.alert.blank? %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.alert %>
    </div>
  <% end %>
<% end %>
<% unless current_user.current_account.padma.try(:attendance_enabled) %>
  <div class="alert alert-danger">--- Attendance disabled ---</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav id="navbar-1" class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">PADMA</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul id="menu-top-left" class="nav navbar-nav">
      <li></li>
      <li><a href="<%= APP_CONFIG['crm-url']%>">CRM</a></li>
      <li><a href="<%= APP_CONFIG['accounts-url']%>">Accounts</a></li>
      <li><a href="<%= APP_CONFIG['support-url']%>">Centro de Ayuda</a></li>
      <li><a href="<%= APP_CONFIG['fnz-url']%>">Financiero</a></li>
    </ul>
    <ul id="menu-top-right" class="nav navbar-nav navbar-right">
      <li><a id="username" href="<%= APP_CONFIG['accounts-url']%>"><img src="https://secure.gravatar.com/avatar/d55ef2d05b82c322260a7148e4b8d6bb.gif?d=<%= APP_CONFIG['crm-url']%>/assets/header_sessionbox_userpicture.png&r=PG&s=21">
        <%= current_user.username %>[<%=current_user.current_account.name %>]
        </a></li>
      <li>
        <%= link_to logout_url do %>
          <span class="glyphicon glyphicon-off"></span><span class="translation_missing" title="translation missing: es.logout"></span>
        <% end %>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav> 


<nav id="navbar-2" class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex2-collapse">
      <span class="sr-only">Attendance</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse navbar-ex2-collapse">
    <ul class="nav navbar-nav">
      <%= link_to image_tag('logo_30px.png'), root_url, class: "navbar-brand fix-logo-height hidden-xs" %>
      <%= content_tag :li, link_to(t('layouts.navbar.attendances'), attendances_url), class: ('active' if controller_name == 'attendances') %>
      <%= content_tag :li, link_to(t('layouts.navbar.time_slots'), time_slots_url), class: ('active' if controller_name == 'time_slots') %>
      <%= content_tag :li, link_to(t('layouts.navbar.trial_lessons'), trial_lessons_url), class: ('active' if controller_name == 'trial_lessons') %>
      <%= content_tag :li, link_to(t('layouts.navbar.stats'), stats_url), class: ('active' if controller_name == 'stats') %>
    </ul>
  </div>
</nav> 

app/views/layouts/_support_button.html.erb
<style>
    #PadmaSupportHub #emailButton {
        position: fixed;
        right: 20px;
        bottom: 20px;
        width: 50px;
        opacity: 0.85;
    }
</style>
<div id="PadmaSupportHub">
  <!-- image url is CRM image -->
  <%= link_to image_tag("icons8-help-100.png", id: "emailButton"), "https://help.derose.app", target: "_blank" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "- Aulas - PADMA" %></title>
  <%= favicon_link_tag "/favicon.ico" %>
  <script src="https://unpkg.com/stimulus@1.1.0/dist/stimulus.umd.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>

  <div id='content' class='container'>
    <div class='row'>
      <div class='col-xs-12 col-md-12' id='flash_messages'>
        <%= render 'layouts/flash_messages' %>
      </div>
      <div class='col-xs-12 col-md-12'>
        <%= yield %>
      </div>
    </div>
  </div>

  <footer class='text-center margin-top-30'>
  </footer>
  <%= render "layouts/support_button" %>
</body>
</html>